### ISSUE TITLE
Setting KanBan 

### ISSUE THREAD

**Issue by BonkeGcobo** [ahangarha/Space-Travelers-Hub#25]
We are a team of two members @BonkeGcobo  and @ahangarha

@BonkeGcobo 
Will be responsible for working on the rocket part of the project.

@ahangarha 
Will be responsible for working on the mission part of the project 

Link to the Kanban project: https://github.com/ahangarha/Space-Travelers-Hub/projects/1

**Comment by FrederickMih** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted an issue, that doesn't contain a link to your Github project. You need to submit an issue with a link to your Github project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by dasileker** [comment]
### **Hi @ahangarha,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
